backend:
  name: github
  repo: Hurricane-Zanka/Hurricane-Zanka.github.io
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    extension: "md"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "標題", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime", default: "{{now}}"}
      - {label: "封面圖", name: "image", widget: "image"}
      - {label: "內文", name: "body", widget: "markdown"}
  
  - name: "gallery"
    label: "圖片庫"
    folder: "gallery"
    create: true
    fields:
      - {label: "圖片", name: "image", widget: "image"}
      - {label: "描述", name: "description", widget: "string"}
